name: 'Handle commands in PR comments'

on:
  issue_comment:
    types: [created]

jobs:
  rebase-pr:
    if: github.repository == 'robotology/cer'
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Rebase PR
      uses: drdanz/gh-action-rebase@pr_from_fork
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        randaz81_TOKEN: ${{ secrets.randaz81_TOKEN }}
        Nicogene_TOKEN: ${{ secrets.Nicogene_TOKEN }}
        elandini84_TOKEN: ${{ secrets.elandini84_TOKEN }}

  squash-pr:
    if: github.repository == 'robotology/cer'
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Squash PR
      uses: robotology/gh-action-squash@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        randaz81_TOKEN: ${{ secrets.randaz81_TOKEN }}
        Nicogene_TOKEN: ${{ secrets.Nicogene_TOKEN }}
        elandini84_TOKEN: ${{ secrets.elandini84_TOKEN }}
